# Generated by Django 5.2.10 on 2026-01-18 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CfgCabo',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nome do Cabo')),
                ('coeficiente', models.FloatField(verbose_name='Coeficiente')),
                ('preco', models.FloatField(default=0.0, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Configuração de Cabo',
                'verbose_name_plural': 'Configurações de Cabos',
            },
        ),
        migrations.CreateModel(
            name='CfgIP',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nome do IP')),
                ('potencia_watts', models.FloatField(verbose_name='Potência (Watts)')),
                ('preco', models.FloatField(default=0.0, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Configuração de IP',
                'verbose_name_plural': 'Configurações de IPs',
            },
        ),
        migrations.CreateModel(
            name='CfgPerfil',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nome do Perfil')),
                ('cqt_max', models.FloatField(blank=True, null=True, verbose_name='CQT Máximo')),
                ('sobrecarga_max', models.FloatField(blank=True, null=True, verbose_name='Sobrecarga Máxima')),
                ('metros_max', models.FloatField(blank=True, null=True, verbose_name='Metros Máximos')),
                ('clientes_max', models.IntegerField(blank=True, null=True, verbose_name='Clientes Máximos')),
            ],
            options={
                'verbose_name': 'Configuração de Perfil',
                'verbose_name_plural': 'Configurações de Perfis',
            },
        ),
        migrations.CreateModel(
            name='CfgTrafo',
            fields=[
                ('kva', models.FloatField(primary_key=True, serialize=False, verbose_name='KVA do Trafo')),
            ],
            options={
                'verbose_name': 'Configuração de Trafo',
                'verbose_name_plural': 'Configurações de Trafos',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Projeto')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='CenarioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cenario', models.CharField(max_length=255, verbose_name='Nome do Cenário')),
                ('trafo_kva', models.IntegerField(blank=True, null=True, verbose_name='Trafo kVA')),
                ('classe_tipo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Classe Tipo')),
                ('classe_manual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Classe Manual')),
                ('fp_ip', models.FloatField(default=0.92, verbose_name='FP IP')),
                ('perfil', models.CharField(default='Padrão (Urbano)', max_length=255, verbose_name='Perfil')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cenarios', to='siscqt_core.projeto')),
            ],
            options={
                'verbose_name': 'Configuração de Cenário',
                'verbose_name_plural': 'Configurações de Cenários',
                'unique_together': {('projeto', 'nome_cenario')},
            },
        ),
        migrations.CreateModel(
            name='Trecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cenario', models.CharField(max_length=255, verbose_name='Nome do Cenário')),
                ('ponto', models.CharField(max_length=255, verbose_name='Ponto')),
                ('montante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Montante')),
                ('metros', models.FloatField(blank=True, null=True, verbose_name='Metros')),
                ('cabo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cabo')),
                ('mono', models.IntegerField(default=0, verbose_name='Mono')),
                ('bi', models.IntegerField(default=0, verbose_name='Bi')),
                ('tri', models.IntegerField(default=0, verbose_name='Tri')),
                ('tri_esp', models.IntegerField(default=0, verbose_name='Tri Especial')),
                ('carga_esp', models.FloatField(blank=True, null=True, verbose_name='Carga Específica')),
                ('tipo_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo IP')),
                ('qtd_ip', models.IntegerField(default=0, verbose_name='Quantidade IP')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='siscqt_core.projeto')),
            ],
            options={
                'verbose_name': 'Trecho',
                'verbose_name_plural': 'Trechos',
                'indexes': [models.Index(fields=['projeto', 'nome_cenario'], name='siscqt_core_projeto_007392_idx')],
                'unique_together': {('projeto', 'nome_cenario', 'ponto')},
            },
        ),
    ]
